---
title: "Analysis"
author: "Alex Jenke"
date: "2024-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(visdat)
```

## Get the dataset and check the na values
```{r}
tuesdata <- read.csv("./data/patient_risk_profiles.csv")
```
## Rename all the columns to increasing numbers to make it easier to visualize how much of the data is missing as opposed to what data is missing. That is, so the column names do not distract from the visualization.

```{r}
columns <- colnames(tuesdata) %>%
    set_names() %>%
    as_tibble() %>%
    mutate(column_number = row_number()) %>%
    pull(column_number)
visualization_df <- tuesdata %>%
    set_names(columns)
vis_miss(visualization_df, show_perc_col = FALSE)

present_percent <- visualization_df %>%
    summarise_all(~sum(!is.na(.))/n()) %>%
    gather() %>%
    pull(value) %>%
    first()
```
## As can be seen also in the visualization above, ```r present_percent```% of the data is present.